version: 1.0.{build}

image: 
  - Visual Studio 2019
  - Ubuntu
  - macOS

before_build:
  - nuget restore

artifacts:
  - path: test.zip
    name: CoreTestProject

after_build:
  7z a test.zip %APPVEYOR_BUILD_FOLDER%/CoreTestProject/bin/Debug/netcoreapp3.1/*
